export { default as DataExplorer} from  './DataExplorer/DataExplorer.vue'
export { default as UMAP} from  './Umap/Umap.vue'
export {default as ProportionPlot} from './ProportionPlot/Proportion.vue'
export {default as GeneExpression} from './GeneExpressionViewer/GeneExpressionViewer.vue'
import 'pennsieve-visualization/style.css'